[general]
fullscreen = true
early-exit = true
initial-tool = "crop"
copy-command = "wl-copy"
output-filename = "/home/pivogirl/Картинки/Screenshots/satty-$(date '+%d%m%Y-%H:%M:%S').png"
save-after-copy = false
default-hide-toolbars = true
primary-highlighter = "block"
disable-notifications = false